### ISSUE TITLE
Prev/Next button not sticking

### ISSUE THREAD

**Issue by Xavier-IV** [Xavier-IV/homelab.day#6]
Some document when navigating to the next guide, will shift the prev/next button up or down.

Ideally this should stick, as I don't have to move my mouse cursor around a few pixel.

**Comment by Vishal-Gori** [comment]
Hello @Xavier-IV ,
I have made the Prev/Next Button Stick by making CardFooter sticky you can review my PR and please merge #8

**Comment by Xavier-IV** [comment]
Awesome, thank you for helping with this!

Merged and deploying this
